name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ''
            archive: tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ''
            archive: tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: '.exe'
            archive: zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add target
        run: rustup target add ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/subtitle_renamer${{ matrix.ext }} dist/
          cd dist
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip subtitle_renamer-${{ matrix.target }}.zip subtitle_renamer${{ matrix.ext }}
          else
            tar czf subtitle_renamer-${{ matrix.target }}.tar.gz subtitle_renamer${{ matrix.ext }}
          fi
          cd ..

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
